export const PROMPT_KEYS = {
  SENTIMENT: 'sentiment',
  ARGUMENTATION: 'argumentation',
  EMOTION: 'emotion',   
  BIAS: 'bias',
  ETHICS: 'ethics',
  TONE_OF_VOICE: 'tone-of-voice',
  INTENTION: 'intention',
  SHORTEN_TEXT: 'shorten-text',
  EXPAND_TEXT: 'expand-text',
  LIST_TO_TEXT: 'list-to-text',
  TEXT_TO_LIST: 'text-to-list',
  SUMMARIZE_TEXT: 'summarize-text',
  EXTRACT_KEY_INSIGHTS: 'extract-key-insights',
  EXPLAIN_TEXT: 'explain-text',
  FIND_PAINPOINTS: 'find-painpoints',
  IMAGE_IDEAS: 'image-ideas',
  SIMPLE_LANGUAGE: 'simple-language',
  COMPLEX_LANGUAGE: 'complex-language',
  MORE_EMOTIONS: 'more-emotions',
  BETTER_STORYTELLING: 'better-storytelling',
  FIND_PERSONA: 'find-persona',
  CAMPAIGN_ANGLES: 'campaign-angles',
  HEADLINE_IDEAS: 'headline-ideas',
  IDEA_FEEDBACK: 'idea-feedback',
  FIND_INTENTIONS: 'find-intentions',
  FIND_TOPICS: 'find-topics',
};
